### ISSUE TITLE
SaveLoadScreen.cs error report

### ISSUE THREAD

**Issue by greenTeaFrappe** [greenTeaFrappe/ToyProject#30]
-select.cs : ScriptOutput scriptOutput = new ScriptOutput(); >> 오류 발생하지 않음
-SaveLoadScreen.cs : ScriptOutput scriptOutput = new ScriptOutput(); >> 같은 구문을 사용하였지만 MonoBehaviour는 생성자를 사용할 수 없다는 경고 발생

오류 해결을 위해 시도한 방법 
-AnyScript anyScript=gameObject.AddComponent<AnyScript>(); 구조 사용
-MonoBehaviour 제거
>>둘 다 실패함

**Comment by CheHyeonYeong** [comment]
save, load 클릭시 뒤 배경이 클릭 됨
보이게 되었을 때 mouse on click 메소드 안되게

**Comment by CheHyeonYeong** [comment]
public class ScriptOutput : MonoBehaviour
이 cs 파일 보시면 해결 가능 할 것 같아요 아래 if문을 잘 다뤄봅시다!!


    private void Update()
    {
        if(!scrollRect.gameObject.activeSelf && !backBtn.gameObject.activeSelf&& logBtn.gameObject.activeSelf && !isButtonClicked)
        {
            // 마우스 클릭 감지
            if (Input.GetMouseButtonDown(0) || Input.GetKeyDown("space"))
            {
                HandleMouseClick();
                    //클릭 처리
            }
        }
    }
