### ISSUE TITLE
[BUG]넘기기 버튼 관련 버그

### ISSUE THREAD

**Issue by greenTeaFrappe** [greenTeaFrappe/ToyProject#45]
## 어떤 버그인가요?

> 게임 시작 직후 넘기기 버튼을 클릭하면 스크립트가 한번 넘어간 후에 정상 작동함

## 어떤 상황에서 발생한 버그인가요?

> DEMO Scene 시작 - 넘기기 버튼 클릭 - New text -> Text1 - 넘기기 버튼 클릭 - 기능 정상 작동

## 예상 결과

> New text에서 바로 버튼으로 가는 것을 예상하였음

**Comment by CheHyeonYeong** [comment]
요거 아직도 해결이 안됐나요?

**Comment by CheHyeonYeong** [comment]
나 이거 해결했어!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1

**Comment by CheHyeonYeong** [comment]
헤헤 다시 시도^^
